include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = Toggle

Toggle_FILES = Toggle.m
Toggle_FRAMEWORKS = Foundation UIKit
Toggle_INSTALL_PATH = /var/mobile/Library/SBSettings/Toggles/ScreenRecToggle

include $(THEOS_MAKE_PATH)/library.mk